import express, { Request, Response } from "express";
import cors from "cors";
import { CurrentStatus, RequestedPriority } from "@prisma/client";
import { getPrisma } from "./prisma.js";

// The Express app is exported separately from app.listen() (see index.ts)
// so Supertest can import `app` without opening a port.
export const app = express();

app.use(cors());
app.use(express.json());

// ---------------------------------------------------------------------------
// Issue 2 — API health check
// ---------------------------------------------------------------------------

app.get("/api/health", (_req: Request, res: Response) => {
  res.status(200).json({
    status: "ok",
    service: "TokTickIT API",
  });
});

// ---------------------------------------------------------------------------
// Issue 4 — Category list
// ---------------------------------------------------------------------------
// GET /api/categories
// Returns categories from PostgreSQL, ordered by ID.
// ---------------------------------------------------------------------------

app.get("/api/categories", async (_req: Request, res: Response) => {
  try {
    const prisma = getPrisma();

    const categories = await prisma.category.findMany({
      where: {
        isActive: true,
      },
      orderBy: {
        id: "asc",
      },
      select: {
        id: true,
        name: true,
      },
    });

    res.status(200).json(categories);
  } catch (error) {
    console.error("Failed to fetch categories:", error);
    res.status(500).json({
      error: "Failed to fetch categories",
    });
  }
});

// ---------------------------------------------------------------------------
// Development Requester list
// ---------------------------------------------------------------------------
// GET /api/requesters
// Returns active development requesters with id, name, and email.
// ---------------------------------------------------------------------------

app.get("/api/requesters", async (_req: Request, res: Response) => {
  try {
    const prisma = getPrisma();

    const requesters = await prisma.developmentRequester.findMany({
      where: {
        isActive: true,
      },
      orderBy: {
        id: "asc",
      },
      select: {
        id: true,
        name: true,
        email: true,
      },
    });

    res.status(200).json(requesters);
  } catch (error) {
    console.error("Failed to fetch requesters:", error);

    res.status(500).json({
      error: "REQUESTERS_UNAVAILABLE",
    });
  }
});

// ---------------------------------------------------------------------------
// Issue 14 — Create Ticket
// ---------------------------------------------------------------------------
// POST /api/tickets
//
// The selected Development Requester is communicated through
// X-Requester-Id.
//
// The requesterId in the request body must match X-Requester-Id.
//
// Ticket Number is generated by the backend:
//
// TCK-YYYYMMDD-NNNN
//
// New tickets always start with Current Status = NEW.
// ---------------------------------------------------------------------------

app.post("/api/tickets", async (req: Request, res: Response) => {
  const requesterHeader = req.header("X-Requester-Id");

  // -------------------------------------------------------------------------
  // Validate requester header
  // -------------------------------------------------------------------------

  if (!requesterHeader) {
    return res.status(400).json({
      error: "Validation failed",
      details: ["X-Requester-Id header is required"],
    });
  }

  const requesterId = Number(requesterHeader);

  if (!Number.isInteger(requesterId) || requesterId <= 0) {
    return res.status(400).json({
      error: "Validation failed",
      details: ["X-Requester-Id must be a valid integer"],
    });
  }

  // -------------------------------------------------------------------------
  // Read request body
  // -------------------------------------------------------------------------

  const {
    requesterId: bodyRequesterId,
    categoryId,
    relatedSystemId,
    summary,
    description,
    requestedPriority,
  } = req.body;

  const details: string[] = [];

  // -------------------------------------------------------------------------
  // Validate requester ID
  // -------------------------------------------------------------------------

  if (!Number.isInteger(bodyRequesterId) || bodyRequesterId <= 0) {
    details.push("requesterId must be a valid integer");
  }

  if (bodyRequesterId !== requesterId) {
    details.push("requesterId must match X-Requester-Id");
  }

  // -------------------------------------------------------------------------
  // Validate Category
  // -------------------------------------------------------------------------

  if (!Number.isInteger(categoryId) || categoryId <= 0) {
    details.push("categoryId must be a valid integer");
  }

  // -------------------------------------------------------------------------
  // Validate Related System
  // -------------------------------------------------------------------------

  if (!Number.isInteger(relatedSystemId) || relatedSystemId <= 0) {
    details.push("relatedSystemId must be a valid integer");
  }

  // -------------------------------------------------------------------------
  // Validate and trim Summary
  // -------------------------------------------------------------------------

  const trimmedSummary =
    typeof summary === "string" ? summary.trim() : "";

  if (trimmedSummary.length < 5 || trimmedSummary.length > 200) {
    details.push("Summary must be between 5 and 200 characters");
  }

  // -------------------------------------------------------------------------
  // Validate and trim Description
  // -------------------------------------------------------------------------

  const trimmedDescription =
    typeof description === "string" ? description.trim() : "";

  if (
    trimmedDescription.length < 10 ||
    trimmedDescription.length > 2000
  ) {
    details.push(
      "Description must be between 10 and 2000 characters"
    );
  }

  // -------------------------------------------------------------------------
  // Validate Requested Priority
  // -------------------------------------------------------------------------

  if (
    requestedPriority !== "LOW" &&
    requestedPriority !== "MEDIUM" &&
    requestedPriority !== "HIGH"
  ) {
    details.push(
      "requestedPriority must be LOW, MEDIUM, or HIGH"
    );
  }

  // -------------------------------------------------------------------------
  // Return validation errors
  // -------------------------------------------------------------------------

  if (details.length > 0) {
    return res.status(400).json({
      error: "Validation failed",
      details,
    });
  }

  try {
    const prisma = getPrisma();

    // -----------------------------------------------------------------------
    // Validate active requester
    // -----------------------------------------------------------------------

    const requester = await prisma.developmentRequester.findFirst({
      where: {
        id: requesterId,
        isActive: true,
      },
      select: {
        id: true,
        name: true,
        email: true,
      },
    });

    if (!requester) {
      return res.status(400).json({
        error: "Validation failed",
        details: [
          "Requester does not exist or is inactive",
        ],
      });
    }

    // -----------------------------------------------------------------------
    // Validate active Category
    // -----------------------------------------------------------------------

    const category = await prisma.category.findFirst({
      where: {
        id: categoryId,
        isActive: true,
      },
      select: {
        id: true,
        name: true,
      },
    });

    if (!category) {
      return res.status(400).json({
        error: "Validation failed",
        details: [
          "Category does not exist or is inactive",
        ],
      });
    }

    // -----------------------------------------------------------------------
    // Validate active Related System
    // -----------------------------------------------------------------------

    const relatedSystem = await prisma.relatedSystem.findFirst({
      where: {
        id: relatedSystemId,
        isActive: true,
      },
      select: {
        id: true,
        name: true,
      },
    });

    if (!relatedSystem) {
      return res.status(400).json({
        error: "Validation failed",
        details: [
          "Related System does not exist or is inactive",
        ],
      });
    }

    // -----------------------------------------------------------------------
    // Create Ticket
    // -----------------------------------------------------------------------

    const ticket = await prisma.$transaction(async (tx) => {
      const ticketDate = new Date();

      // Generate YYYYMMDD using UTC.
      const year = ticketDate.getUTCFullYear();

      const month = String(
        ticketDate.getUTCMonth() + 1
      ).padStart(2, "0");

      const day = String(
        ticketDate.getUTCDate()
      ).padStart(2, "0");

      const datePart = `${year}${month}${day}`;

      const prefix = `TCK-${datePart}-`;

      // Prevent simultaneous requests from generating
      // the same sequence number.
      await tx.$executeRaw`
        SELECT pg_advisory_xact_lock(hashtext(${prefix}))
      `;

      // Count today's tickets.
      const ticketCount = await tx.ticket.count({
        where: {
          ticketNumber: {
            startsWith: prefix,
          },
        },
      });

      const sequenceNumber = ticketCount + 1;

      if (sequenceNumber > 9999) {
        throw new Error(
          "Daily ticket number limit reached"
        );
      }

      const ticketNumber =
        `${prefix}${String(sequenceNumber).padStart(4, "0")}`;

      return tx.ticket.create({
        data: {
          ticketNumber,
          ticketDate,

          requesterId,
          categoryId,
          relatedSystemId,

          summary: trimmedSummary,
          description: trimmedDescription,

          requestedPriority:
            requestedPriority as RequestedPriority,

          currentStatus: CurrentStatus.NEW,
        },

        include: {
          requester: {
            select: {
              id: true,
              name: true,
              email: true,
            },
          },

          category: {
            select: {
              id: true,
              name: true,
            },
          },

          relatedSystem: {
            select: {
              id: true,
              name: true,
            },
          },

          attachments: true,
        },
      });
    });

    // -----------------------------------------------------------------------
    // Successful creation
    // -----------------------------------------------------------------------

    return res.status(201).json(ticket);
  } catch (error) {
    console.error("Failed to create ticket:", error);

    return res.status(500).json({
      error: "Failed to create ticket",
    });
  }
});

// ---------------------------------------------------------------------------

export default app;